### ISSUE TITLE
한줄평 영역 이미지 

### ISSUE THREAD

**Issue by carami** [connect-boostcamp/reservation-system#55]
@mixed  
https://github.com/connect-boostcamp/reservation-system/blob/master/task/%EC%98%88%EB%A7%A4%EC%9E%90_%ED%95%9C%EC%A4%84%ED%8F%89.md 

여기 이미지가 안보인다고....  질문이 있었습니다.  
앞 태스크의 한줄평영역과 같다고 안내는 하였는데,  혹시 이미지 링크 수정해 주실 수 있으시면 해주세요^^

**Comment by mixed** [comment]
네 수정했습니다.
